/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IscrizionePackage;
import LoginPackage.SchermataLogin;
import LoginPackage.LoginControl;
/**
 *
 * @author manfredi
 */
public class CampoTipologia extends javax.swing.JFrame {
    
    /**
     * Creates new form CampiIscrizione
     */
    SchermataLogin schermataLogin;
    LoginControl loginControl;
    String tipologia;
    public CampoTipologia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IndietroButton = new javax.swing.JButton();
        RappresentanteButton = new javax.swing.JButton();
        DiocesiButton = new javax.swing.JButton();
        AziendaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleziona il tipo di utente che deve iscriversi");

        IndietroButton.setText("Indietro");
        IndietroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndietroButtonActionPerformed(evt);
            }
        });

        RappresentanteButton.setText("Rappresentante del Polo");
        RappresentanteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RappresentanteButtonActionPerformed(evt);
            }
        });

        DiocesiButton.setText("Diocesi");
        DiocesiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiocesiButtonActionPerformed(evt);
            }
        });

        AziendaButton.setText("Azienda");
        AziendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AziendaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AziendaButton)
                    .addComponent(DiocesiButton)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(IndietroButton)
                        .addComponent(RappresentanteButton)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(RappresentanteButton)
                .addGap(18, 18, 18)
                .addComponent(DiocesiButton)
                .addGap(18, 18, 18)
                .addComponent(AziendaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(IndietroButton)
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RappresentanteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RappresentanteButtonActionPerformed
        // TODO add your handling code here:
        this.tipologia = "Rappresentante del Polo";
        this.loginControl.createCampoDati();
    }//GEN-LAST:event_RappresentanteButtonActionPerformed

    private void DiocesiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiocesiButtonActionPerformed
        // TODO add your handling code here:
        this.tipologia = "Diocesi";
        this.loginControl.createCampoDati();
    }//GEN-LAST:event_DiocesiButtonActionPerformed

    private void AziendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AziendaButtonActionPerformed
        // TODO add your handling code here:
        this.tipologia = "Azienda";
        this.loginControl.createCampoDati();
    }//GEN-LAST:event_AziendaButtonActionPerformed

    private void IndietroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndietroButtonActionPerformed
        // TODO add your handling code here:
        this.schermataLogin.mostra();
        this.setVisible(false);
       
    }//GEN-LAST:event_IndietroButtonActionPerformed
    
    public String getTipologia(){
        return this.tipologia;
    }
    
    public void mostra(LoginControl lg){
        this.loginControl = lg;
        this.schermataLogin = this.loginControl.getSchermata();
        this.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CampoTipologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CampoTipologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CampoTipologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CampoTipologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CampiIscrizione().setVisible(true);
            }
        });
        //</editor-fold>
        
        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CampiIscrizione().setVisible(true);
            }
        });
    */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AziendaButton;
    private javax.swing.JButton DiocesiButton;
    private javax.swing.JButton IndietroButton;
    private javax.swing.JButton RappresentanteButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
