/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package IscrizionePackage;

import LoginPackage.LoginControl;
/**
 *
 * @author manfredi
 */
public class PopUpConferma extends javax.swing.JFrame {

    /**
     * Creates new form PopUpConferma
     */
    
    LoginControl loginControl;
    CampoDatiAzienda iscrizioneAzienda;
    CampoDatiDiocesi iscrizioneDiocesi;
    CampoDatiRappresentantePolo iscrizioneRappresentante;
    String tipologia;
    
    public PopUpConferma() {
        initComponents();
    }
    
    public void mostra(LoginControl lg){
        this.loginControl = lg;
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        confermaButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idGeneratoDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dati inseriti correttamente");

        confermaButton.setText("Conferma");
        confermaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confermaButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Il tuo id univoco per effettuare il login è -->");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(confermaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idGeneratoDisplay)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idGeneratoDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(confermaButton)
                .addGap(48, 48, 48))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confermaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confermaButtonActionPerformed
        this.setVisible(false);
        if(this.tipologia.equals("Azienda")){
            this.iscrizioneAzienda.setVisible(false);
             this.loginControl.schermata.mostra();
        }
        else if(this.tipologia.equals("Rappresentante")){
            this.iscrizioneRappresentante.setVisible(false);
            this.loginControl.schermata.mostra();
        }
        else if(this.tipologia.equals("Diocesi")){
            this.iscrizioneDiocesi.setVisible(false);
            this.loginControl.schermata.mostra();
        }
    }//GEN-LAST:event_confermaButtonActionPerformed
    
    
    public void mostra(LoginControl lg, CampoDatiAzienda ca, String id){
        this.setVisible(true);
        this.loginControl = lg;
        this.iscrizioneAzienda = ca;
        this.tipologia = "Azienda";
        this.idGeneratoDisplay.setText(String.valueOf(id));
    }
    
    public void mostra(LoginControl lg, CampoDatiRappresentantePolo cr, String id){
        this.setVisible(true);
        this.loginControl = lg;
        this.iscrizioneRappresentante = cr;
        this.tipologia = "Rappresentante";
        this.idGeneratoDisplay.setText(String.valueOf(id));
    }
    
    public void mostra(LoginControl lg, CampoDatiDiocesi cd, String id){
        this.setVisible(true);
        this.loginControl = lg;
        this.iscrizioneDiocesi = cd;
        this.tipologia = "Diocesi";
        this.idGeneratoDisplay.setText(String.valueOf(id));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUpConferma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUpConferma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUpConferma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUpConferma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUpConferma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confermaButton;
    private javax.swing.JLabel idGeneratoDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
