/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IscrizionePackage;
import LoginPackage.*;
/**
 *
 * @author manfredi
 */
public class PopUpErrore extends javax.swing.JFrame {

    /**
     * Creates new form PopUpErr
     */
    CampoDatiRappresentantePolo schermataRappr;
    CampoDatiDiocesi schermataDiocesi;
    CampoDatiAzienda schermataAzienda;
    LoginControl loginControl;
    
    boolean errorRappresentante;
    boolean errorDiocesi;
    boolean errorAzienda;
    
    public PopUpErrore() {
        initComponents();
        this.errorAzienda = false;
        this.errorDiocesi = false;
        this.errorAzienda = false;
    }
    
    public void mostraErrore(CampoDatiRappresentantePolo campoRappresentante, LoginControl lg){
        this.setVisible(true);
        this.schermataRappr = campoRappresentante;
        this.loginControl = lg;
    }
    
    public void mostraErrore(CampoDatiDiocesi campoDiocesi, LoginControl lg){
        this.setVisible(true);
        this.schermataDiocesi = campoDiocesi;
        this.loginControl = lg;
    }
    
    public void mostraErrore(CampoDatiAzienda campoAzienda, LoginControl lg){
        this.setVisible(true);
        this.schermataAzienda = campoAzienda;
        this.loginControl = lg;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IndietroButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IndietroButton.setText("Indietro");
        IndietroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndietroButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Errore durante l'inserimento dati");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(IndietroButton)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(IndietroButton)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IndietroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndietroButtonActionPerformed
        this.setVisible(false);
        if(this.errorAzienda)
            this.schermataAzienda.mostra(this.loginControl);
        else if(this.errorDiocesi)
            this.schermataDiocesi.mostra(this.loginControl);
        else if(this.errorRappresentante)
            this.schermataRappr.mostra(this.loginControl); 
    }//GEN-LAST:event_IndietroButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUpErrore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUpErrore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUpErrore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUpErrore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IndietroButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
