/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ConsegnaViveriPackage;

/**
 *
 * @author manfredi
 */
public class PopUp extends javax.swing.JFrame {

    /**
     * Creates new form InserimentoViveri
     */
    
    ConsegnaViveriControl viveriControl;
    
    public PopUp() {
        initComponents();
    }
    
    //Chiamato quando si clicca ok per inserire il prossimo vivere
    public void mostraConferma(ConsegnaViveriControl viveriControl){
        this.viveriControl = viveriControl;
        testo2.setVisible(true);
        IndietroButton.setVisible(false);
        testo1.setVisible(false);
        Ok2.setVisible(true);
        this.setVisible(true);
    }
    //Chiamato quando si devono inserire i viveri nel database
    public void mostraConferma(ConsegnaViveriControl viveriControl, boolean operation){
        this.viveriControl = viveriControl;
        if(operation){
            testo1.setVisible(false);
            IndietroButton.setVisible(false);
            testo2.setVisible(true);
            Ok2.setVisible(false);
            this.setVisible(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testo1 = new javax.swing.JLabel();
        testo2 = new javax.swing.JLabel();
        Ok2 = new javax.swing.JButton();
        IndietroButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        testo1.setText("Operazione Fallita");

        testo2.setText("Operazione Riuscita");

        Ok2.setText("Ok");
        Ok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ok2ActionPerformed(evt);
            }
        });

        IndietroButton.setText("Indietro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testo2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(testo1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ok2)
                            .addComponent(IndietroButton))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testo2)
                .addGap(3, 3, 3)
                .addComponent(testo1)
                .addGap(18, 18, 18)
                .addComponent(IndietroButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ok2))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
   
    //L'ok che fa ricomparire in loop inserimento dati viveri
    private void Ok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ok2ActionPerformed
        this.setVisible(false);
        this.viveriControl.counter++;
        this.viveriControl.inserisciViveri();
    }//GEN-LAST:event_Ok2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IndietroButton;
    private javax.swing.JButton Ok2;
    private javax.swing.JLabel testo1;
    private javax.swing.JLabel testo2;
    // End of variables declaration//GEN-END:variables
}
