/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SchermataPrincipalePackage;
import LoginPackage.EntityUtente;
import GestioneAccount.GestioneAccountControl;
import GestioneMagazzinoPackage.GestioneMagazzinoControl;
import GestioneFamiglie.GestioneFamiglieControl;
/**
 *
 * @author manfredi
 */

public class SchermataPrincipaleRappresentante extends javax.swing.JFrame {
   
    public EntityUtente utente;
    GestioneAccountControl gestioneAccountControl;
    GestioneMagazzinoControl gestioneMagazzinoControl;
    GestioneFamiglieControl gestioneFamiglieControl;
    /**
     * Creates new form SchermataPrincipale
     */
    public SchermataPrincipaleRappresentante() {
        initComponents();
    }
    
    public void mostra(EntityUtente utente){
        this.setVisible(true);
        this.utente = utente;
    }
    
    public void mostra(){
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        GestioneAccountButton = new javax.swing.JButton();
        GestioneMagazzinoButton = new javax.swing.JButton();
        GestioneFamigliaButton = new javax.swing.JButton();
        ScaricaSchemaDistribuzioneButton = new javax.swing.JButton();
        ScaricoMagazzinoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Schermata Principale Rappresentante del Polo");

        GestioneAccountButton.setText("Gestione Account");
        GestioneAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestioneAccountButtonActionPerformed(evt);
            }
        });

        GestioneMagazzinoButton.setText("Gestione Magazzino");
        GestioneMagazzinoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestioneMagazzinoButtonActionPerformed(evt);
            }
        });

        GestioneFamigliaButton.setText("Gestione Famiglia");
        GestioneFamigliaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestioneFamigliaButtonActionPerformed(evt);
            }
        });

        ScaricaSchemaDistribuzioneButton.setText("Scarica Schema Distribuzione");
        ScaricaSchemaDistribuzioneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScaricaSchemaDistribuzioneButtonActionPerformed(evt);
            }
        });

        ScaricoMagazzinoButton.setText("Scarico Magazzino");
        ScaricoMagazzinoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScaricoMagazzinoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GestioneAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(GestioneFamigliaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ScaricaSchemaDistribuzioneButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ScaricoMagazzinoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GestioneMagazzinoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GestioneAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GestioneMagazzinoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GestioneFamigliaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ScaricaSchemaDistribuzioneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScaricoMagazzinoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GestioneMagazzinoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestioneMagazzinoButtonActionPerformed
        this.gestioneMagazzinoControl = new GestioneMagazzinoControl(this);
        this.gestioneMagazzinoControl.createGestioneMagazzinoBND(this);
        
    }//GEN-LAST:event_GestioneMagazzinoButtonActionPerformed

    private void ScaricaSchemaDistribuzioneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScaricaSchemaDistribuzioneButtonActionPerformed
        this.gestioneAccountControl = new GestioneAccountControl(this);
        this.gestioneAccountControl.richiediSchema(true);

    }//GEN-LAST:event_ScaricaSchemaDistribuzioneButtonActionPerformed

    private void ScaricoMagazzinoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScaricoMagazzinoButtonActionPerformed
        this.gestioneMagazzinoControl = new GestioneMagazzinoControl(this);
        this.gestioneMagazzinoControl.datiMagazzino(true);
    }//GEN-LAST:event_ScaricoMagazzinoButtonActionPerformed

    private void GestioneFamigliaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestioneFamigliaButtonActionPerformed
        this.gestioneFamiglieControl = new GestioneFamiglieControl(this);
        this.gestioneFamiglieControl.createGestioneFamigliaBND();
    }//GEN-LAST:event_GestioneFamigliaButtonActionPerformed

    private void GestioneAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestioneAccountButtonActionPerformed
        this.gestioneAccountControl = new GestioneAccountControl(this);
        this.gestioneAccountControl.createGestioneAccountBoundary();
    }//GEN-LAST:event_GestioneAccountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchermataPrincipaleRappresentante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchermataPrincipaleRappresentante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchermataPrincipaleRappresentante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchermataPrincipaleRappresentante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchermataPrincipaleRappresentante().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GestioneAccountButton;
    private javax.swing.JButton GestioneFamigliaButton;
    private javax.swing.JButton GestioneMagazzinoButton;
    private javax.swing.JButton ScaricaSchemaDistribuzioneButton;
    private javax.swing.JButton ScaricoMagazzinoButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
