/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SchermataPrincipalePackage;
import GestioneAccount.GestioneRichiesteBND;
import GestioneAccount.GestioneAccountControl;
import LoginPackage.EntityUtente;
import ConsegnaViveriPackage.*;
/**
 *
 * @author manfredi
 */
public class SchermataPrincipaleAzienda extends javax.swing.JFrame {

    /**
     * Creates new form SchermataPrincipaleAzienda
     */
    public EntityUtente utente;
    AggiungiDonazioneSchermata aggiungiDonazione;
    ConsegnaViveriControl viveriControl = new ConsegnaViveriControl(this);
    GestioneRichiesteBND gestioneRichieste = new GestioneRichiesteBND();
    GestioneAccountControl gestioneRichiesteControl = new GestioneAccountControl();
    
    public SchermataPrincipaleAzienda() {
        initComponents();
    }

    public void mostra(EntityUtente utente){
        this.setVisible(true);
        this.utente = utente;
    }
    
    public void mostra(){
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AggiungiDonazioneButton = new javax.swing.JButton();
        GestioneRichiesteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Schermata Principale Azienda");

        AggiungiDonazioneButton.setText("Aggiungi Donazione");
        AggiungiDonazioneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AggiungiDonazioneButtonActionPerformed(evt);
            }
        });

        GestioneRichiesteButton.setText("Gestione Richieste");
        GestioneRichiesteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestioneRichiesteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(AggiungiDonazioneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GestioneRichiesteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel1)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AggiungiDonazioneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GestioneRichiesteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AggiungiDonazioneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AggiungiDonazioneButtonActionPerformed
        this.aggiungiDonazione = this.viveriControl.createAggiungiDonazione();
        this.aggiungiDonazione.mostra(this.viveriControl, this);
        this.setVisible(false);
    }//GEN-LAST:event_AggiungiDonazioneButtonActionPerformed

    private void GestioneRichiesteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestioneRichiesteButtonActionPerformed
        this.gestioneRichiesteControl.createGestioneRichieste(this.utente, this);
        this.setVisible(false);
    }//GEN-LAST:event_GestioneRichiesteButtonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchermataPrincipaleAzienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchermataPrincipaleAzienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchermataPrincipaleAzienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchermataPrincipaleAzienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchermataPrincipaleAzienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AggiungiDonazioneButton;
    private javax.swing.JButton GestioneRichiesteButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
