/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SchermataPrincipalePackage;
import LoginPackage.EntityUtente;
import GestioneSistemaPackage.GestioneSistemaControl;
/**
 *
 * @author manfredi
 */
public class SchermataPrincipaleAmministratore extends javax.swing.JFrame {

    /**
     * Creates new form SchermataPrincipaleAmministratore
     */
    public EntityUtente utente;
    GestioneSistemaControl gestioneSistemaControl;
    public SchermataPrincipaleAmministratore() {
        initComponents();
    }
    
    public void mostra(EntityUtente utente){
        this.setVisible(true);
        this.utente = utente;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        visualizzaErroriButton = new javax.swing.JButton();
        eliminaAccountButton = new javax.swing.JButton();
        visualizzaReportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Schermata Principale Amministratore");

        visualizzaErroriButton.setText("Visualizza Errori");
        visualizzaErroriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizzaErroriButtonActionPerformed(evt);
            }
        });

        eliminaAccountButton.setText("Elimina Account");
        eliminaAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaAccountButtonActionPerformed(evt);
            }
        });

        visualizzaReportButton.setText("Visualizza Report");
        visualizzaReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizzaReportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(visualizzaErroriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(eliminaAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(visualizzaReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(250, 250, 250))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visualizzaErroriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminaAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visualizzaReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void visualizzaErroriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizzaErroriButtonActionPerformed
        this.gestioneSistemaControl = new GestioneSistemaControl(this);
        this.gestioneSistemaControl.createVisualizzaErrori();
    }//GEN-LAST:event_visualizzaErroriButtonActionPerformed

    private void eliminaAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaAccountButtonActionPerformed
        this.gestioneSistemaControl = new GestioneSistemaControl(this);
        this.gestioneSistemaControl.createSelezionaTipologia();
    }//GEN-LAST:event_eliminaAccountButtonActionPerformed

    private void visualizzaReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizzaReportButtonActionPerformed
        this.gestioneSistemaControl = new GestioneSistemaControl(this);
        this.gestioneSistemaControl.createVisualizzaReport();
    }//GEN-LAST:event_visualizzaReportButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchermataPrincipaleAmministratore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchermataPrincipaleAmministratore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchermataPrincipaleAmministratore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchermataPrincipaleAmministratore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchermataPrincipaleAmministratore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminaAccountButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton visualizzaErroriButton;
    private javax.swing.JButton visualizzaReportButton;
    // End of variables declaration//GEN-END:variables
}
