/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SchermataPrincipalePackage;
import LoginPackage.EntityUtente;
import GestioneMagazzinoPackage.ControlloErroriBND;
import GestioneMagazzinoPackage.GestioneMagazzinoControl;
import GestioneAccount.GestioneAccountControl;

/**
 *
 * @author manfredi
 */

public class SchermataPrincipaleDiocesi extends javax.swing.JFrame {
    public EntityUtente utente;
    public ControlloErroriBND controlloErrori = new ControlloErroriBND();
    public GestioneMagazzinoControl gestioneMagazzinoControl;
    public GestioneAccountControl gestioneAccountControl;
    /**
     * Creates new form SchermataPrincipaleDiocesi
     */
    public SchermataPrincipaleDiocesi() {
        initComponents();
    }

    public void mostra(EntityUtente utente){
        this.setVisible(true);
        this.utente = utente;
    }
    
    public void mostra(){
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ControlloErroriButton = new javax.swing.JButton();
        ScaricaSchemaDonazioniButton = new javax.swing.JButton();
        ScaricoMagazzinoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Schermata Principale Diocesi");

        ControlloErroriButton.setText("Controllo Errori");
        ControlloErroriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlloErroriButtonActionPerformed(evt);
            }
        });

        ScaricaSchemaDonazioniButton.setText("Scarica Schema Donazione");
        ScaricaSchemaDonazioniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScaricaSchemaDonazioniButtonActionPerformed(evt);
            }
        });

        ScaricoMagazzinoButton.setText("Scarico Magazzino");
        ScaricoMagazzinoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScaricoMagazzinoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(ControlloErroriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(ScaricaSchemaDonazioniButton)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(ScaricoMagazzinoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ControlloErroriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScaricaSchemaDonazioniButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(ScaricoMagazzinoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ControlloErroriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlloErroriButtonActionPerformed
        this.gestioneMagazzinoControl = new GestioneMagazzinoControl(this);
        this.gestioneMagazzinoControl.richiediErrori();
        this.setVisible(false);
    }//GEN-LAST:event_ControlloErroriButtonActionPerformed
    
    private void ScaricoMagazzinoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScaricoMagazzinoButtonActionPerformed
        this.gestioneMagazzinoControl = new GestioneMagazzinoControl(this);
        this.gestioneMagazzinoControl.datiMagazzino();
    }//GEN-LAST:event_ScaricoMagazzinoButtonActionPerformed

    private void ScaricaSchemaDonazioniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScaricaSchemaDonazioniButtonActionPerformed
        this.gestioneAccountControl = new GestioneAccountControl(this);
        this.gestioneAccountControl.richiediSchema();
        
        
    }//GEN-LAST:event_ScaricaSchemaDonazioniButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchermataPrincipaleDiocesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchermataPrincipaleDiocesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchermataPrincipaleDiocesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchermataPrincipaleDiocesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchermataPrincipaleDiocesi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ControlloErroriButton;
    private javax.swing.JButton ScaricaSchemaDonazioniButton;
    private javax.swing.JButton ScaricoMagazzinoButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
