/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GestioneAccount;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author manfredi
 */
public class VisualizzaDateBND extends javax.swing.JFrame {

    /**
     * Creates new form VisualizzaDateBND
     */
    
    GestioneAccountControl gestioneAccountControl;
    
    public VisualizzaDateBND() {
        initComponents();
    }

    public void mostra(GestioneAccountControl gestioneAccountControl){
        this.gestioneAccountControl = gestioneAccountControl;
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TrimestraleButton = new javax.swing.JButton();
        SemestraleButton = new javax.swing.JButton();
        AnnualeButton = new javax.swing.JButton();
        IndietroButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleziona l'arco di tempo per il report");

        TrimestraleButton.setText("Trimestrale");
        TrimestraleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrimestraleButtonActionPerformed(evt);
            }
        });

        SemestraleButton.setText("Semestrale");
        SemestraleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemestraleButtonActionPerformed(evt);
            }
        });

        AnnualeButton.setText("Annuale");
        AnnualeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnualeButtonActionPerformed(evt);
            }
        });

        IndietroButton.setText("Indietro");
        IndietroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndietroButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TrimestraleButton)
                        .addGap(85, 85, 85)
                        .addComponent(SemestraleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(AnnualeButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(IndietroButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TrimestraleButton)
                    .addComponent(SemestraleButton)
                    .addComponent(AnnualeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(IndietroButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IndietroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndietroButtonActionPerformed
       this.gestioneAccountControl.schermataRappresentante.mostra();
    }//GEN-LAST:event_IndietroButtonActionPerformed

    private void TrimestraleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrimestraleButtonActionPerformed
        int id = this.gestioneAccountControl.schermataRappresentante.utente.getIdUtente();
        this.gestioneAccountControl.richiediReportDate(id,3);
        this.setVisible(false);
    }//GEN-LAST:event_TrimestraleButtonActionPerformed

    private void SemestraleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemestraleButtonActionPerformed
        int id = this.gestioneAccountControl.schermataRappresentante.utente.getIdUtente();
        this.gestioneAccountControl.richiediReportDate(id,6);

    }//GEN-LAST:event_SemestraleButtonActionPerformed

    private void AnnualeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnualeButtonActionPerformed
        int id = this.gestioneAccountControl.schermataRappresentante.utente.getIdUtente();
        this.gestioneAccountControl.richiediReportDate(id,1);
    }//GEN-LAST:event_AnnualeButtonActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizzaDateBND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizzaDateBND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizzaDateBND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizzaDateBND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizzaDateBND().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnualeButton;
    private javax.swing.JButton IndietroButton;
    private javax.swing.JButton SemestraleButton;
    private javax.swing.JButton TrimestraleButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
